name: PR create image locally
# This workflow is triggered on pushes to the repository.
on:
  pull_request:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          registry: localhost:5000
          repository: papanito/atlantis-azure
          tag_with_ref: true
      - name: Remove local image
        run: docker image rm localhost:5000/papanito/atlantis-azure:pr

      - name: Run image from registry
        run: docker run localhost:5000/papanito/atlantis-azure:pr