name: PR create image locally
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Branch info
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo $SOURCE_NAME $SOURCE_BRANCH $SOURCE_TAG
          echo $GITHUB_REF
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          registry: localhost:5000
          repository: papanito/atlantis-azure
          tag_with_ref: true
      - name: Remove local image
        run: docker image rm localhost:5000/papanito/atlantis-azure:pr

      - name: Run image from registry
        run: docker run localhost:5000/papanito/atlantis-azure:pr