name: Build and publish docker image
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: papanito/atlantis-azure
          tag_with_ref: true