name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Create release branch
        run: git checkout -b release/$RELEASE_VERSION &&  git push --set-upstream origin release/$RELEASE_VERSION
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "FROM .*"
          replace: "FROM ghcr.io/runatlantis/atlantis:$RELEASE_VERSION"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papanito/atlantis-azure:$RELEASE_VERSION
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "meta: use image version $RELEASE_VERSION"
          file_pattern: ./*
          commit_user_name: My GitHub Actions Bot
          commit_user_email: ci@wyssmann.com
          commit_author: Papanito <papanito@wyssmann.com>
          push_options: --force
